### PR TITLE
feat: add launch for status_display_manager

### PR DESCRIPTION
**Pull request by BaronYSYong**
## Description
* Activating status_display_manager node in launch file
* Update README.md for status_display_manager

## Related links
* https://tier4.atlassian.net/browse/AEAP-989
* https://github.com/tier4/dio_ros_driver/pull/5
* https://github.com/eve-autonomy/status_display_manager/pull/1

## Tests performed
* Steps for building the testing packages:
  * git clone `tier4/autoware.proj.eva.git` and checkout the branch `beta/v4.4.0`
  * `mkdir src` and `vcs import src < autoware.repos`
  * git checkout `dio_ros_driver` to [feat/feat/dio_port_array_setting](https://github.com/kodamays/dio_ros_driver) in `src/x1/vendor`
  * git clone `status_display_manager` and checkout to [main](https://github.com/eve-autonomy/status_display_manager) in `src/x1/vendor`
  * git checkout `proj_lauch` to [feat/add_status_display_manager_launch](https://github.com/eve-autonomy/proj_launch/tree/feat/add_status_display_manager_launch) in `src/x1/launcher`
  * Build the package with `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --continue-on-error`
* A test was conducted with running Psim (PC simulator) to verify `status_display_manager` is launched correctly with `proj_launch`, when proj_launch is executed. The test ensured that `status_display_manager` is properly initiated as shown as rqt_graph below.
status_display_manager_rosgraph_2
* We have confirmed the function worked as stated in [status_display_manager specification](https://github.com/eve-autonomy/status_display_manager?tab=readme-ov-file#overview)
  * [Testing result](https://eva.app.box.com/file/1701005317325) 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by peeeechi** [comment]
> - feat: add di/do array interface and processing tier4/dio_ros_driver#5
> - feat(status_display_manager): add package status_display_manager#1

Please move these items from the "Notes for reviewers" section to the "Related links" section.

**Comment by peeeechi** [comment]
> The test ensured that status_display_manager was properly initialized as shown in the rqt_graph below.

Please provide evidence for this verification.
For example, confirm that:
- Input topics to `/status_display_manager` conform to the pre-defined (or newly added) interfaces
- Nodes subscribing to output topics from `/status_display_manager` align with the specified interface requirements

**Comment by BaronYSYong** [comment]
> > The test ensured that status_display_manager was properly initialized as shown in the rqt_graph below.
> 
> Please provide evidence for this verification. For example, confirm that:
> 
> * Input topics to `/status_display_manager` conform to the pre-defined (or newly added) interfaces
> * Nodes subscribing to output topics from `/status_display_manager` align with the specified interface requirements

Added in at the bottom of Test Performed
Screenshot from 2024-11-21 18-30-36

**Review by yn-mrse — APPROVED** [review]

**Comment by peeeechi** [comment]
LGTM!!!!

**Pull request merged**
